name: .NET Core

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Build
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Deploy
      run: dotnet nuget push "**/bin/Release/*.nupkg" -k ${{ secrets.NUGET_DEPLOY_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate




