name: .NET Core

on:
  pull_request:
    branches: [ main, release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Build
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Upload build
    - uses: actions/upload-artifact@v2
      with:
        name: dotnet-build
        path: ${{ github.workspace }}/**/bin/Release/**
  
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Build
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: dotnet-build

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: test
      run: dotnet test --no-build --configuration Release


